# Generated by Django 4.2 on 2023-04-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=200)),
                ('deptimage', models.ImageField(upload_to='images')),
                ('year', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
