# Generated by Django 4.2 on 2023-04-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('empno', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('proimage', models.ImageField(upload_to='images')),
                ('prodecription', models.TextField()),
                ('deptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.departments')),
            ],
        ),
    ]
