# Generated by Django 4.2 on 2023-04-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_departmenthead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthead',
            name='deptname',
            field=models.CharField(max_length=200),
        ),
    ]
