# Generated by Django 4.2 on 2023-04-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_departmenthead_deptname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=200)),
                ('empno', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('proimage', models.ImageField(upload_to='images')),
                ('prodescription', models.TextField()),
                ('deptname', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='departmenthead',
            old_name='prodecription',
            new_name='prodescription',
        ),
    ]
