# Generated by Django 4.2 on 2023-04-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthead',
            name='deptname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.departments'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='deptname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.departments'),
        ),
    ]
